# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_material', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=40, null=True)),
                ('google_scholars', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(default=b'IN', max_length=2)),
                ('state_of_origin', models.CharField(default=b'Rajasthan', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female'), (b'o', b'Other')], max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications', models.TextField(blank=True, max_length=10000, null=True)),
                ('alma_mater', models.CharField(blank=True, max_length=800, null=True)),
                ('areas_of_interest', models.TextField(blank=True, max_length=5000, null=True)),
                ('working_experience', models.TextField(blank=True, max_length=2000, null=True)),
                ('publications', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='assignedcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
