# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('days_given', models.IntegerField(blank=True, null=True)),
                ('ref_books', models.TextField(blank=True, max_length=500, null=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('credits', models.IntegerField(blank=True, default=0, null=True)),
                ('classification', models.CharField(choices=[(b'Theory', b'Theory'), (b'Lab', b'LAB')], default=b'th', max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[(b'I', b'Semester I'), (b'II', b'Semester II'), (b'III', b'Semester III'), (b'IV', b'Semester IV'), (b'V', b'Semester V'), (b'VI', b'Semester VI'), (b'VII', b'Semester VII'), (b'VIII', b'Semester VIII')], default=b'Semester I', max_length=15, null=True)),
                ('spi', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.Semester'),
        ),
    ]
