# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classification',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'LAB')], default='th', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, choices=[('I', 'Semester I'), ('II', 'Semester II'), ('III', 'Semester III'), ('IV', 'Semester IV'), ('V', 'Semester V'), ('VI', 'Semester VI'), ('VII', 'Semester VII'), ('VIII', 'Semester VIII')], default='Semester I', max_length=15, null=True),
        ),
    ]
