# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=4, null=True)),
                ('instructor_remarks', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cpi', models.CharField(blank=True, max_length=10, null=True)),
                ('guardians_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[(b'a+', b'A+'), (b'b+', b'B+'), (b'ab', b'AB'), (b'ab+', b'AB+'), (b'o', b'O'), (b'o+', b'O+'), (b'o-', b'O-')], max_length=3, null=True)),
                ('application_number', models.CharField(blank=True, max_length=9, null=True)),
                ('academic_year', models.CharField(default=b'2017-18', max_length=7, null=True)),
                ('programme', models.CharField(choices=[(b'ug_cse', b'B.Tech.(CS)'), (b'ug_it', b'B.Tech.(IT)'), (b'pg_cs', b'M.Tech.(CS)'), (b'pg_it', b'M.Tech.(IT)')], default=b'ug_cse', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female'), (b'o', b'Other')], max_length=1, null=True)),
                ('social_category', models.CharField(choices=[(b'gen', b'General'), (b'obc', b'OBC'), (b'sc', b'SC'), (b'st', b'ST'), (b'pwd', b'PwD')], default=b'gen', max_length=3, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=16, null=True)),
                ('country', django_countries.fields.CountryField(default=b'IN', max_length=2)),
                ('state_of_origin', models.CharField(default=b'Rajasthan', max_length=20, null=True)),
                ('qualifying_board', models.CharField(default=b'Central Board of Secondary Education', max_length=100, null=True)),
                ('qualifying_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifying_exam_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifying_exam_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, null=True)),
                ('last_school', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_rank', models.CharField(blank=True, max_length=6, null=True)),
                ('tenth_marks', models.CharField(blank=True, max_length=6, null=True)),
                ('tenth_passing_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2015, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='regcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.RegCourse'),
        ),
    ]
