# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
