# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='2017-18', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('b+', 'B+'), ('ab', 'AB'), ('ab+', 'AB+'), ('o', 'O'), ('o+', 'O+'), ('o-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('ug_cse', 'B.Tech.(CS)'), ('ug_it', 'B.Tech.(IT)'), ('pg_cs', 'M.Tech.(CS)'), ('pg_it', 'M.Tech.(IT)')], default='ug_cse', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualifying_board',
            field=models.CharField(default='Central Board of Secondary Education', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_category',
            field=models.CharField(choices=[('gen', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('pwd', 'PwD')], default='gen', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(default='Rajasthan', max_length=20, null=True),
        ),
    ]
